import type {
  DeleteSourceChunksOptions,
  DeleteSourceChunksResult,
  DeterministicClassifierConfig,
  Embedder,
  ForgetOptions,
  ForgetResult,
  IndexedSourceChunk,
  IndexSourceChunksOptions,
  PristineLocalConfig,
  RecalledMemory,
  RecallOptions,
  RevealResult,
  SearchSourceChunksOptions,
  SecureAndRedactResult,
  SourceChunkInput,
  SourceChunkMetadata,
  SourceChunkNormalizeOptions,
  SourceChunkSearchHit,
  SourceChunkSearchOptions,
  SourceChunkStoreOptions,
  StoredMemory,
  StoredSourceChunk,
  StoreOptions,
} from '@pristine/shield-local';

type PublicRootTypes = [
  DeleteSourceChunksOptions,
  DeleteSourceChunksResult,
  DeterministicClassifierConfig,
  Embedder,
  ForgetOptions,
  ForgetResult,
  IndexedSourceChunk,
  IndexSourceChunksOptions,
  PristineLocalConfig,
  RecalledMemory,
  RecallOptions,
  RevealResult,
  SearchSourceChunksOptions,
  SecureAndRedactResult,
  SourceChunkInput,
  SourceChunkMetadata,
  SourceChunkNormalizeOptions,
  SourceChunkSearchHit,
  SourceChunkSearchOptions,
  SourceChunkStoreOptions,
  StoredMemory,
  StoredSourceChunk,
  StoreOptions,
];

const publicRootTypesFixture: PublicRootTypes | null = null;
void publicRootTypesFixture;
