import { createRegexRule, isJwt, type BuiltInRule } from './rule-helpers.js';

export const BUILT_IN_RULES: readonly BuiltInRule[] = [
  createRegexRule({
    ruleId: 'private-key.pem-block',
    kind: 'private_key_block',
    pattern:
      /-----BEGIN (?:RSA |EC |ED25519 |OPENSSH |DSA )?PRIVATE KEY-----[\s\S]*?-----END (?:RSA |EC |ED25519 |OPENSSH |DSA )?PRIVATE KEY-----/g,
    suggestedType: 'private_key',
    positiveSignals: ['private_key_block', 'detector_confidence_high'],
    priority: 5,
    minSensitivity: 2,
  }),
  createRegexRule({
    ruleId: 'private-key.pgp-block',
    kind: 'private_key_block',
    pattern: /-----BEGIN PGP PRIVATE KEY BLOCK-----[\s\S]*?-----END PGP PRIVATE KEY BLOCK-----/g,
    suggestedType: 'private_key',
    positiveSignals: ['private_key_block', 'detector_confidence_high'],
    priority: 5,
    minSensitivity: 2,
  }),
  createRegexRule({
    ruleId: 'assignment.sensitive-key',
    kind: 'key_value_assignment',
    pattern:
      /\b([A-Z0-9_]*(?:API[_-]?KEY|ACCESS[_-]?TOKEN|AUTH[_-]?TOKEN|SECRET|PASSWORD|PRIVATE[_-]?KEY)[A-Z0-9_]*)\s*[:=]\s*['"]?([A-Za-z0-9][A-Za-z0-9._~+/=-]{7,})['"]?/gi,
    valueGroup: 2,
    nearbyNameGroup: 1,
    suggestedType: 'secret',
    positiveSignals: ['sensitive_key_name'],
    priority: 3,
    minSensitivity: 1,
  }),
  createRegexRule({
    ruleId: 'header.authorization-bearer',
    kind: 'auth_header',
    pattern: /\bAuthorization\s*:\s*Bearer\s+([A-Za-z0-9._~+/=-]{16,})\b/gi,
    valueGroup: 1,
    suggestedType: 'auth_token',
    positiveSignals: ['auth_header_context'],
    features: { headerName: 'authorization' },
    priority: 4,
    minSensitivity: 2,
  }),
  createRegexRule({
    ruleId: 'provider.aws-access-key-id',
    kind: 'known_provider_prefix',
    pattern: /\bAKIA[0-9A-Z]{16}\b/g,
    suggestedType: 'api_key',
    provider: 'aws',
    prefixFamily: 'AKIA',
    positiveSignals: ['known_provider_prefix'],
    priority: 4,
    minSensitivity: 2,
  }),
  createRegexRule({
    ruleId: 'provider.github-token',
    kind: 'known_provider_prefix',
    pattern: /\b(?:ghp_|gho_|ghs_)[A-Za-z0-9]{36}\b/g,
    suggestedType: 'api_key',
    provider: 'github',
    prefixFamily: 'ghp_',
    positiveSignals: ['known_provider_prefix'],
    priority: 3,
    minSensitivity: 2,
  }),
  createRegexRule({
    ruleId: 'provider.openai-project-key',
    kind: 'known_provider_prefix',
    pattern: /\bsk-proj-[A-Za-z0-9_-]{20,}\b/g,
    suggestedType: 'api_key',
    provider: 'openai',
    prefixFamily: 'sk-proj',
    positiveSignals: ['known_provider_prefix'],
    priority: 3,
    minSensitivity: 2,
  }),
  createRegexRule({
    ruleId: 'provider.anthropic-key',
    kind: 'known_provider_prefix',
    pattern: /\bsk-ant-[A-Za-z0-9_-]{20,}\b/g,
    suggestedType: 'api_key',
    provider: 'anthropic',
    prefixFamily: 'sk-ant',
    positiveSignals: ['known_provider_prefix'],
    priority: 3,
    minSensitivity: 2,
  }),
  createRegexRule({
    ruleId: 'provider.sendgrid-key',
    kind: 'known_provider_prefix',
    pattern: /\bSG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}\b/g,
    suggestedType: 'api_key',
    provider: 'sendgrid',
    prefixFamily: 'SG.',
    positiveSignals: ['known_provider_prefix'],
    priority: 3,
    minSensitivity: 2,
  }),
  createRegexRule({
    ruleId: 'structured.jwt',
    kind: 'structured_token',
    pattern: /\b(eyJ[A-Za-z0-9_-]+\.eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_.+/=-]*)\b/g,
    valueGroup: 1,
    suggestedType: 'auth_token',
    positiveSignals: ['structured_token'],
    features: { tokenFormat: 'jwt' },
    validate: isJwt,
    priority: 3,
    minSensitivity: 2,
  }),
  createRegexRule({
    ruleId: 'structured.paseto',
    kind: 'structured_token',
    pattern: /\b(v[24]\.(?:local|public)\.[A-Za-z0-9_-]{20,})\b/g,
    valueGroup: 1,
    suggestedType: 'auth_token',
    positiveSignals: ['structured_token'],
    features: { tokenFormat: 'paseto' },
    priority: 3,
    minSensitivity: 2,
  }),
  createRegexRule({
    ruleId: 'url.credential-password',
    kind: 'credential_url',
    pattern: /[a-z][a-z0-9+.-]*:\/\/[^:\s/@]+:([^@\s]+)@/gi,
    valueGroup: 1,
    suggestedType: 'password',
    positiveSignals: ['credential_url_context'],
    priority: 4,
    minSensitivity: 2,
  }),
  createRegexRule({
    ruleId: 'cookie.session-token',
    kind: 'cookie_or_session',
    pattern: /\b(?:sessionid|session|sid|connect\.sid|jwt|token)=([A-Za-z0-9._~+/=-]{12,})\b/gi,
    valueGroup: 1,
    suggestedType: 'auth_token',
    positiveSignals: ['cookie_context'],
    priority: 3,
    minSensitivity: 1,
  }),
  createRegexRule({
    ruleId: 'query.signed-url-secret',
    kind: 'signed_url_or_query_secret',
    pattern:
      /[?&](?:X-Amz-Signature|X-Amz-Credential|sig|signature|token|access_token|api_key|key|secret)=([^&\s]+)/gi,
    valueGroup: 1,
    suggestedType: 'auth_token',
    positiveSignals: ['query_secret_param'],
    priority: 4,
    minSensitivity: 2,
  }),
  createRegexRule({
    ruleId: 'cloud.aws-secret-access-key',
    kind: 'cloud_credential_block',
    pattern:
      /\b(AWS_SECRET_ACCESS_KEY|aws_secret_access_key)\s*[:=]\s*['"]?([A-Za-z0-9/+=]{32,64})['"]?/g,
    valueGroup: 2,
    nearbyNameGroup: 1,
    suggestedType: 'api_key',
    provider: 'aws',
    positiveSignals: ['cloud_credential_block', 'sensitive_key_name'],
    priority: 4,
    minSensitivity: 2,
  }),
  createRegexRule({
    ruleId: 'seed.recovery-phrase',
    kind: 'recovery_or_seed_phrase',
    pattern:
      /\b(?:seed phrase|recovery phrase|mnemonic)\s*[:=]\s*((?:[a-z]+[\s,]+){11,23}[a-z]+)/gi,
    valueGroup: 1,
    suggestedType: 'recovery_phrase',
    positiveSignals: ['recovery_phrase_context'],
    priority: 4,
    minSensitivity: 2,
  }),
  createRegexRule({
    ruleId: 'opaque.generated-looking-value',
    kind: 'opaque_generated_value',
    pattern: /\b[A-Za-z0-9_-]{32,}\b/g,
    suggestedType: 'secret',
    positiveSignals: ['opaque_generated_value'],
    priority: 1,
    minSensitivity: 0,
  }),
];
